### PR TITLE
Add support for leaving some bleed edge, plus some

### PR DESCRIPTION
**Pull request by Malacath-92**
Changes in this PR:
- Use OpenCV for cropping, saving and loading (still uses PIL for filters)
  - This makes the cropper 10x faster on my crappy laptop
- Move "Paper Size" and "Orientation" options into a combo-box
- Add a "Bleed Edge (mm)" option (note, maximum 3.05 mm as that's the bleed edge that we start with)
  - Crops into separate folder
  - Draws PDF with adjusted guides
  - Disables "Render PDF" button if cropper needs to run

New settings header
image

Original behavior is maintained at 0mm
0mm

Same page at 1mm bleed edge
1mm

And at 2mm bleed edge
2mm

### CODE REVIEW

**Comment by Malacath-92** [comment]
Forgot about formatting. I didn't do any auto-formatting because I wasn't sure what formatter you used. Just lemme know and I'll take care of it.

**Comment by Malacath-92** [comment]
@preshtildeath It's been two weeks, should I just close this PR and advertise my own fork as an alternative?

**Comment by ltmluis** [comment]
It's your amazing work. I am very grateful for your tool. Could you add an option that adds a space between the cards? Thank you very much again

**Comment by urza-lab** [comment]
@Malacath-92 Thanks for the PR and [your fork](https://github.com/Malacath-92/print-proxy-prep). Some questions to it:

1. Would it be possible to add an option which moves crosshairs "outwards", i.e. towards the bleeding edge? This would leave a user-defined spare space which would be especially useful, when the prints are heartlessly cut with amateur gear in a way that neglects cutting corners, whereas the prints are subsequently being anyway sleeved in front of an original-sized card.
2. If 1. is not possible: Is there a way to change color of the crosshairs/corner angles? I took a look at your PR which replaced RGB codings for the crosshairs, I'd have changed it there but now I am unsure where this would be possible.
3. How can one enforce a certain Paper Size? It defaults always to `Letter` once the project has been deleted, and `Papersize = A4`, `Paper.Size = A4` or `Paper = A4` is not getting picked up from the config file. 

For anyone running into trouble with the fork using `cv2` running Windows 11 KN or N, I will leave the solution that helped me getting the fork running.

> Q: Import fails on Windows: ImportError: DLL load failed: The specified module could not be found.?
> A: Windows N and KN editions **do not include Media Feature Pack** which is required by OpenCV. If you are using Windows N or KN edition, please install also [Windows Media Feature Pack](https://support.microsoft.com/en-us/help/3145500/media-feature-pack-list-for-windows-n-editions).

**Comment by Malacath-92** [comment]
Hiya folks, sorry I didn't get notified for the comments.

@ltmluis I'm not sure what you mean. Instead of the bleed edge being preserved or in addition to it?

@h3rb1n4t0r 
1. Same, not sure what you mean. If the cutting guides are moved out then what is the use for them? They wouldn't guide to cut at the right spot, so instead of moving them you might as well just skip them completely. If that's what you want I can add that too.
2. Perhaps I can add it to the config, should be very easy in theory.
3. Default paper size is also something that can be easily added to the config. I find myself having to change it all the time as well.

And thanks for the workaround for OpenCV, I wasn't aware of this.

**Comment by Malacath-92** [comment]
@h3rb1n4t0r I added the default page size option just now, it's `Paper.Size = A4`

**Comment by urza-lab** [comment]
> 1. Same, not sure what you mean. If the cutting guides are moved out then what is the use for them? They wouldn't guide to cut at the right spot, so instead of moving them you might as well just skip them completely. If that's what you want I can add that too.

The use would be to have some spare paper after cutting, which would serve to make sure that original cards put as "stabilizer" behind the proxy print in a sleeve vanish 100% even though the proxy was cut inaccurately.

Skipping them or also moving them as cutting indicators outside of the card range, i.e. to top/bottom/left/right of the page only, would be a nice feature tho.

Thanks a lot!

EDIT: If I understood @ltmluis correctly, request is to have dark spare space between cards printed which basically corresponds to my 1. question.

**Pull request closed without merging**
